### ISSUE TITLE
Use MarkerCluster

### ISSUE THREAD

**Issue by bennyborn** [numero2/contao-storelocator#27]

**Comment by vmulot** [comment]
Hi there, any news on this one ? :) Thanks for the great job, this plugin is awesome !

**Comment by bennyborn** [comment]
Unfortunately no. We did not have any opportunity to implement that feature yet.

**Comment by stefansl** [comment]
Hi, i did that 7 years ago. But I do not know, if it still works https://github.com/stefansl/storelocator_map

**Comment by bennyborn** [comment]
Hi Stefan. Since we're currently in the process to migrate this extension to a proper Contao 4 bundle alongside some other modifications we can't use any of your code for that. But the feature itself is still on our list :)

**Comment by stefansl** [comment]
Hi benny, I installed it minutes ago :D I don't know, if I need that feature in an updated project, but if yes, I will do a PR. 
Are there any limitions left in the contao4 branch?

**Comment by bennyborn** [comment]
> I don't know if I need that feature in an now updated project, but if yes, I will do a PR.
> Are there any limitions left in the contao4 branch?

PR's are absolutely welcome but the Contao4 branch is pretty much work in progress and still subject to some substantial changes. We're already working on implementing multiple geocoding/map providers so we're not quite sure yet how one should implement something provider specific like MarkerCluster for Google Maps.

Anyway, feel free to get in touch with us and contribute :)
