### ISSUE TITLE
User location on loading

### ISSUE THREAD

**Issue by vmulot** [numero2/contao-storelocator#30]
Hi,
it's not a bug, but i'd like to get User Position (with the browser prompt for geolocation), center Map on it, and get the distance calc for stores around him.
i didn't find if your module can handle that.
i' tried myself, i managed to get user position, centering the map, but i don't have the distance in the store list.

any advice/idea/update? :)

thanks

**Comment by bennyborn** [comment]
Not quite sure if I understand you correctly but the Storelocator itself can tell you the distance to the store from the given location

https://github.com/numero2/contao-storelocator/blob/599d6616b55b9df971d48395f686fb3904d42ed1/templates/modules/mod_storelocator_list.html5#L30-L34

If you'd want to use the browsers location you might add you script to the `mod_storelocator_search.html5` and populate all the hiddens fields (which also contain the coordinates) and submit this form automatically.

That way the user will end up in the results list having all distances shown ;)

**Comment by vmulot** [comment]
Thanks for answering !
i tried your tip but how do you handle the submit  only the first time  and only if coords are available ?
i tried to check the GET params (lat and lng) but it keep submitting form.
`$(document).ready(function(){
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };
                    $('input[name="longitude"]').val(pos.lng);
                    $('input[name="latitude"]').val(pos.lat);
                    $('#<?php echo $this->formId; ?>').submit();
                }, function() {

                });
            } else {
                // Browser doesn't support Geolocation

            }
        });`
Thanks again for your help !
