### ISSUE TITLE
Map-Generierung auf der Detailseite funktioniert nicht. 

### ISSUE THREAD

**Issue by vossmedien** [numero2/contao-storelocator#32]
Liste, Suche usw. funktioniert problemlos.
Nur die Generierung des iFrames auf der Detailseite scheint nicht zu klappen.

`<?= $this->mapsURI; ?>`

wird auch generiert und ergibt einen Wert, dieser ist aber anscheinend nicht korrekt.
Evtl. kann man sich das ja mal ansehen :-) Danke sehr!

**Comment by ManuelaMe** [comment]
Ich habe ein ähnliches Problem. Die Google Map wird auf der Detailseite nicht angezeigt mit folgender Fehlermeldung:

>  Google Maps Platform rejected your request. This API project is not authorized to use this API.

Auf der Listenansicht kann ich die Karte ganz normal sehen. Siehe z.B. https://www.ihredls.de/standorte/standort-details/%C3%B6ko-markt-k%C3%B6ln-rudolfplatz.html
bzw. https://www.ihredls.de/dls-vor-ort.html

**Comment by bennyborn** [comment]
> Ich habe ein ähnliches Problem. Die Google Map wird auf der Detailseite nicht angezeigt mit folgender Fehlermeldung [...]

Scheint so als hättest Du bei den APIs vergessen die `Google Maps Embed API` mit auszuwählen ;)

**Comment by ManuelaMe** [comment]
Vielen Dank, manchmal sieht man vor lauter Wald die Bäume nicht.
