### ISSUE TITLE
Eingabefeld für Google Maps Server/Browser-Schlüssel fehlt in Contao 4.7

### ISSUE THREAD

**Issue by mr2017x** [numero2/contao-storelocator#34]
Hallo,

in Contao 4.7 scheint das Eingabefeld für die Google Maps API Keys nicht mehr verfügbar zu sein. Glücklicherweise ist mir dies nur in einer Testinstallation aufgefallen.

Viele Grüße!

**Comment by bennyborn** [comment]
Danke für die Info, wir kümmern uns drum!

**Comment by mr2017x** [comment]
Dankeschön! :-)
