### ISSUE TITLE
Template selection fails

### ISSUE THREAD

**Issue by asaage** [numero2/contao-storelocator#35]
Contao-version 4.8.3
It's not possible to create any storelocator modules
```log
Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array, string given
```
The getTemplateGroup function changed -> https://github.com/contao/contao/commit/bdc4dd86ff5209bc03a6fbc009e0b6f1c601834f

It's called here -> https://github.com/numero2/contao-storelocator/blob/master/dca/tl_module.php#L421

**Comment by bennyborn** [comment]
Seems to make that the second parameter was a leftover from Contao 3.
Looking at the 4.4 branch there seems to be no second parameter at all:

https://github.com/contao/core-bundle/blob/4.4/src/Resources/contao/library/Contao/Controller.php#L93

The second parameter in 4.8 being optional I guess we're good just to strip it entirely?

**Comment by asaage** [comment]
If i do that only two templates are available and they are not appropriate to the module-type.

Like here for the Händlersuche:

![image](https://user-images.githubusercontent.com/4138336/64965014-820e8c00-d89c-11e9-8392-4fdfc35a0706.png)
