### ISSUE TITLE
Error in Modules

### ISSUE THREAD

**Issue by christianbargon** [numero2/contao-storelocator#40]
When I try to setup a new module (no matter what kind of "Händler" - it produces an Error: 

Contao 4.9 - PHP 7.4

Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array, string given, called in /var/clients/client3/web730/fressnapf/var/cache/prod/contao/dca/tl_module.php on line 2502

**Comment by bennyborn** [comment]
We've not yet made any changes to be compatible with 4.9. Should be no nig problem, give us some time.

**Comment by bennyborn** [comment]
Can you give it a try using the current `HEAD`?
I hope I figured out most of the problems.

**Comment by christianbargon** [comment]
HI Benny, what did you mean with "head" - I updated the package with the Contao-manager. But I still can not create "modules".

Error said: Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array, string given, called in /var/clients/client3/web730/fressnapf/var/cache/prod/contao/dca/tl_module.php on line 2502

**Comment by bennyborn** [comment]
Yeah that's not how it works :)
You can only update it via the Manager once I created a new release but before doing so I wanted to make sure that everything works.

On the "start" page of this repo you can click on "Clone or download" and download a ZIP archive.
In the archive you'll find a folder named `contao-storelocator-master`.
Replace all the files in `system/modules/storelocator` with the ones from the ZIP archive.

And please make sure to delete every StoreLocator Frontend-Module you've created so far. It is important to create a fresh module for the fix to work :)

**Comment by christianbargon** [comment]
Hi Benny, thank you for your help - now I understand completely :-) I will try to install the update and give response! Regards Chris

**Comment by christianbargon** [comment]
Hi Benny, I can create modules now - thank you for you help again - Regards Chris

**Comment by bennyborn** [comment]
Thanks for testing Chris! I'll leave this issue open till the end of the week. If I don't hear back again from you I suppose we fixed all problems. I'm then gonna make a new release which you can install normally using the Contao Manager! :)
