### ISSUE TITLE
GeocodeAPI and Google's restrictions

### ISSUE THREAD

**Issue by stefansl** [numero2/contao-storelocator#44]
If you want to restrict your Google API key on referer urls the Geocode API will not work. Google needs a restriction on IPs -> https://developers.google.com/maps/documentation/geocoding/get-api-key?hl=de

So. If I restrict the API key to my server IP Geocode works, but the Maps API fails, because you need to restrict that key on referer urls.

That's gonna be complicated, because in fact we need two API keys to let it work properly.

**Comment by bennyborn** [comment]
I don't think I'm quite getting the point of your problem. We already have to API keys for the exact same reason. One server key (which should be restricted by IP) and one browser key (that should be restricted by referer).

**Comment by stefansl** [comment]
What the heck :D You're right ... sorry for the noise
