### ISSUE TITLE
Probleme mit Klammern bei Vorschläge anzeigen

### ISSUE THREAD

**Issue by pedal123** [numero2/contao-storelocator#50]
Vielen Dank für das Modul.

Bei der Händlersuche gibt es bei Sonderzeichen einen Fehler und es wird nichts gefunden.

Halle - wird gefunden
Halle (Saale) ergibt Fehler und es werden keine Ergebnisse angezeigt.

Contao 4.13.20
PHP 8.1.22

**Comment by bennyborn** [comment]
Kannst Du mal den Debug-Modus aktivieren und den StackTrace dazu posten?

**Comment by pedal123** [comment]
Danke, das geht ja schnell :).
Ich habe noch einmal nachgesehen, ist das reproduzierbar?
Nach der Auswahl im Suchfeld wird aus 
"Halle, Deutschland" nach der Suche "Halle, Deutschland"
aus
"Halle (Saale) Deutschland" wird "Halle &#40"

**Comment by bennyborn** [comment]
Haben soeben einen Fix commited, wir würden dann morgen einen neuen Release machen 😉

**Comment by pedal123** [comment]
Allerbesten Dank

**Comment by bennyborn** [comment]
Neue Version v4.2.4 wurde soeben veröffentlicht 😉
