### ISSUE TITLE
Doesn't work without Google API key

### ISSUE THREAD

**Issue by Olli** [numero2/contao-storelocator#53]
I've changed the frontend to output a openstreetmap based map with leaflet but in the backend the static map doesn't work without the Google API key. 
This key you only get nowadays if you give them payment information but I'm not willing to do that so the static map doesn't work.
Maybe it's good to disable the map view if no API keys provided.

**Comment by michb** [comment]
We've added the handling for differnt map providers, namely `google maps`, `bing map`, and `here`. 
If one of them is given and configured with the needed keys, we will add a static map of the geocoordinates otherwise we will show an empty gray box.

**Comment by michb** [comment]
I have not found a similar feature in openstreetmap (`nominatim`) that we can use in this place. And I don't like the idea of adding an embeded or javascript map in this place. 
If there is such a feature, I would happily add it.

**Comment by michb** [comment]
We are working on an other feature this week. After that we will make a new release.

**Comment by Olli** [comment]
OK thx
