### ISSUE TITLE
Custom markers are cut off, zip code search not working

### ISSUE THREAD

**Issue by sietsevandreven** [numero2/contao-storelocator#54]
Hello,

We are using this extension to show all pools that are using our certificates. We have currently 264 locations. But the custom markers seem to be cut off for whatever reason. See the attachment (1st one). When I make 2 locations invisible the markers are shown the correct way (2nd attachment). So it seems there is a limit of 262 stores. Is this something I can fix myself? (e.g. informing the cliënt there is a limit of locations), or can you fix this issue.

In addition to this, the zip code search does no longer work when 264 locations are active. It does work with 262 locations active. This is a bigger problem than the markers not showing correctly.

Thanks in advance :)

![image](https://github.com/numero2/contao-storelocator/assets/22072261/49c1fff3-2880-4a2d-b446-256f4122b5f3)
![image](https://github.com/numero2/contao-storelocator/assets/22072261/664c5a24-a511-4b04-be05-50bc80798832)

**Comment by bennyborn** [comment]
Hi @sietsevandreven, to me it looks like there might be a problem with at least one of the two markers you made invisible.

I guess any of these markers contains HTML or special characters that breaks the rest of the markup which would result in a faulty rendering of the pins and the break the search.

Is this site publicly accessible? If not please take a look at the console of the Devtools in your browser.

**Comment by sietsevandreven** [comment]
It doesn't really matter which location I disable for the markers to work again. The website is public (https://www.envoz.nl/voor-ouders/zwemles-in-de-buurt.html). The marker is an SVG. But to me that isn't the issue, because it has worked for a couple of years.

**Comment by bennyborn** [comment]
Interesting... So far I don't see any obvious reason for the behaviour. Would it be possible for you to provide us with a copy of your locations? Feel free to contact me via e-mail at benny.born@numero2.de

**Comment by bennyborn** [comment]
We found a fix for the problem. It seems that Google is trying to optimize the rendering of markers once you reach a certain treshold. The [documentation](https://developers.google.com/maps/documentation/javascript/markers#optimize) states that this could cause problems with animated GIFs or PNGs:

> Not all Markers can be optimized; in some situations, the Maps JavaScript API may need to render Markers without optimization. Disable optimized rendering for animated GIFs or PNGs, or when each marker must be rendered as a separate DOM element.

Obiously this also causes problems when trying to scale SVGs correctly so we disabled the optimization by default which fixed it 😉

**Comment by bennyborn** [comment]
Seems like a bug introduced in c1d9cfc47a87fe10e058cf1ff8a856acac41dc07
We've just released a fix for that.

**Comment by sietsevandreven** [comment]
Works like a charm :) Thanks for the quick response and fixes.
