### ISSUE TITLE
Map invisible on page load

### ISSUE THREAD

**Issue by sietsevandreven** [numero2/contao-storelocator#55]
The Google Map is invisible on page load, only the controls and grey background are visible. When you click on a store tile, the map moves to the location as it should. I cannot find what causes the issue. I replaced all modified templates by original ones.

Contao 4.13.40
PHP 8.1
Storelocator 4.2.9

**Comment by bennyborn** [comment]
Could you, for testing purposes, disable the CSS of your page / theme? I have a strong feeling that there is a styling problem that interferes with Google Maps.

**Comment by sietsevandreven** [comment]
Disabling the style doesn't help...

**Comment by bennyborn** [comment]
Can you confirm that the "gray background" is not just a really far zoomed in map? Are there any errors in your browsers developer console? Any chance of a public link (can be sent via e-mail)?

**Comment by sietsevandreven** [comment]
The map is not zoomed in, the zoom out button is grayed out. The color of the map is the same as the inline background-color. The link is: https://www.envoz.nl/voor-ouders/zwemles-in-de-buurt.html

**Comment by bennyborn** [comment]
It seems like at least one of your markers has some incorrect latitude and longitude values:

![image](https://github.com/numero2/contao-storelocator/assets/226890/7176b946-878c-4a2c-8b20-36f4d5afc13b)

I guess you've imported those values from somewhere else?

**Comment by sietsevandreven** [comment]
That seems to be the problem indeed.

Thank you very much for your time and effort. I think #56 would be a very nice improvement.
