### ISSUE TITLE
Implement front end module

### ISSUE THREAD

**Issue by pixlemedia** [numero2/contao-storelocator#58]
Hi,

i did the whole installation process, set up all APIs, added a business entry and now i would like to publish this location front-end wise. But i can`t find any article element oder modul which offers the possibility to publish my map. The googleMaps module of "premium contao themes" is pre installed but i can`t embed the locations defined by the Store-locator plugin.
Probably noob question but how do I proceed here?

**Comment by bennyborn** [comment]
Our StoreLocator comes with his own set of Frontend Modules:

![image](https://github.com/user-attachments/assets/c3831588-3669-4a73-b5ed-a78d6f2b621e)

**Comment by pixlemedia** [comment]
Thanks for your support!
That`s the way i expected. But these FE-modules does not show up in my list.
StoreLocator 4.3.0, C4.9.42 is in use / installtool successfully finished after installation via contao-manager / "Händler" entry under Backend Contents visible and my DB includes tl_storelocator categories, tl_dtorelocator_stores. What the hack could have been gone wrong on my end and how to solve this?

**Comment by bennyborn** [comment]
I don't think you did anything wrong. If the extension is installed successfully, all database tables are there and there is `Händler` in the backend navigation the only thing I can think of is that any other extension messes up the module options.

**Comment by pixlemedia** [comment]
Thats hard to believe:
I deleted all extensions including StoreLocator and reinstalled StoreLocator again / Deleted prod cache / browser cache and run through system maintenance process. Unfortunately same story as before. Do you have any other ideas regarding this issue? I am really looking forward to use your extension but i am really stuck right now ...

**Comment by bennyborn** [comment]
Maybe just give us a quick call ([numero2.de](https://numero2.de)) and we'll look into it together with you 😉
